### ISSUE TITLE
`Docker-compose.yml`: Add prefix to service and container name

### ISSUE THREAD

**Issue by luca-rigutti** [pieroit/cheshire-cat#163]
Hi,

If there is not problem with something else on the code, I suggest to add a prefix to service and container to avoid collision with other service used with docker.

An example of this can be:

```yaml
  cheshire-cat-core:
      build:
        context: ./core
      container_name: cheshire_cat_core
```

And also for the `admin` and `vector-memory`

Thanks
